name: Deploy to Firefox Add-on Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Disable workflow
    if: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Patch minor version
        run: |
          npm version --no-git-tag-version --allow-same-version patch
          echo "VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build extension
        run: npm run build

      - name: Sign and submit web extension
        working-directory: "dist"
        env:
          WEB_EXT_API_KEY: ${{ secrets.FF_WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.FF_WEB_EXT_API_SECRET }}
        run: npx web-ext-submit --api-key="$WEB_EXT_API_KEY" --api-secret="$WEB_EXT_API_SECRET"
