name: Run tests for form-filler

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        # There is a bug in Jest that when running in Linux environments it fails
        # to run a test with fetch. It says that fetch is not defined. This is a
        # workaround to fix this issue.
        run: npm test -- --runInBand